package com.example.dynamoxchallenge.constants

    const val CARD_RESULT_MESSAGE = "Sua pontuação foi"
    const val WELCOME_MESSAGE = "bem vindo, "
    const val BUTTON_TITLE_NEXT_QUESTION_MESSAGE = "Próxima Questão"
    const val BUTTON_TITLE_RESULT_MESSAGE = "Resultado"
    const val OUTLINED_BUTTON_PLAY_AGAIN_MESSAGE = "Jogar novamente"
    const val OUTLINED_BUTTON_PLAY_MESSAGE = "Jogar"
    const val GET_NEW_QUESTION_MESSAGE = "Carregando nova pergunta"
    const val ASK_WORD = "ASK"
    const val ME_WORK = "ME"
    const val RIGHT_ANSWER_MESSAGE = "Resposta certa"
    const val WRONG_ANSWER_MESSAGE = "Resposta errada"
    const val TEXT_FIELD_MESSAGE = "Insira o seu nome/apelido"
    const val CONGRATULATIONS_MESSAGE = "Parabéns "
    const val ALTERNATIVE_MESSAGE = "Alternativas"
    const val TRY_AGAIN_MESSAGE = "Tentar novamente"
    const val ERROR_MESSAGE = "Ooops"
    const val RANKINK_MESSAGE = "Ranking"
    const val BACK_MESSAGE = "Voltar"
    const val DEFAULT_RANKING_PAGE_MESSAGE = "Jogue mais de três vezes para ver o ranking"
    const val CHECK_ANSWER_MESSAGE = "Verificar resposta"